// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSxakUKGehhfylygO3LXoGhbirfl0Iepw',
    appId: '1:354848765001:android:6cb4ba65e455a7dc5d3b98',
    messagingSenderId: '354848765001',
    projectId: 'hk-translate-1744f',
    storageBucket: 'hk-translate-1744f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAas8FkUI7YBUOhAX7Cave7vg-lb0Bpoww',
    appId: '1:354848765001:ios:a44943466d4a70105d3b98',
    messagingSenderId: '354848765001',
    projectId: 'hk-translate-1744f',
    storageBucket: 'hk-translate-1744f.appspot.com',
    androidClientId: '354848765001-f25p2agbhasu8kbfld6tud4g6j3l710i.apps.googleusercontent.com',
    iosClientId: '354848765001-dpacthvqatb55v4mj8lq2a2bkvahmgj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoPurchase',
  );

}